### ISSUE TITLE
Implementation of DctStem

### ISSUE THREAD

**Issue by chiachunho** [wuyang45/MCAN_code#1]
Hi Yang Wu, 

Very much thanks for that you made the repository of MCAN public recently.

I would like to ask a question about the implementation of DctStem that is utilized in DctCNN (cell 7 of 12 in [MCAN.ipynb](https://github.com/wuyang45/MCAN_code/blob/main/MCAN.ipynb)).

DctStem is not implemented or imported from packages in the notebook file, can you commit the code of the DctStem or provide references?

It will be beneficial if you are willing to reply to this issue.

Thank you and sorry for bothering you.

**Comment by java123321** [comment]
Dear Mr. wu yang, I am a graduate student in Harbin Engineering University who studies multimodal false news. We have recently repeated the baseline work on multimodal false news detection. We have seen that your article "Multimodal Fusion with Co-Attention Networks for Fake News Detection" has open source code on the hub, but a function implementation of DctStem is missing in the code. I don't know if the upperclassman missed the upload. We want to hold a try mentality to ask the seniors there is no code implementation of the function. This will be a great help to our recovery work. Thanks!
